#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# setup_cron_qr_tx_display3in7g.sh
#
# Purpose:
#   Create start_qr_tx_display3in7g.sh and register it to cron @reboot.
#
# Target:
#   /home/yamalog-8/Desktop/QRe-paper/api/qr_tx_display3in7g.py
# ============================================================

PROJECT_DIR="/home/yamalog-8/Desktop/QRe-paper"
API_DIR="${PROJECT_DIR}/api"
VENV_PY="${PROJECT_DIR}/venv/bin/python3"
PY_SCRIPT="${API_DIR}/qr_tx_display3in7g.py"
START_SCRIPT="${PROJECT_DIR}/start_qr_tx_display3in7g.sh"
LOG_DIR="${PROJECT_DIR}/logs"
STARTUP_LOG="${LOG_DIR}/qr_tx_display3in7g_startup.log"
CRON_LOG="${LOG_DIR}/cron_qr_tx_display3in7g.log"

EPAPER_BASE_DIR="${PROJECT_DIR}/e-Paper/waveshare-e-Paper-latest/E-paper_Separate_Program/3in7_e-Paper_G/RaspberryPi_JetsonNano/python"

CRON_LINE="@reboot ${START_SCRIPT} >> ${CRON_LOG} 2>&1"

echo "============================================================"
echo "Setup cron for qr_tx_display3in7g.py"
echo "PROJECT_DIR=${PROJECT_DIR}"
echo "PY_SCRIPT=${PY_SCRIPT}"
echo "START_SCRIPT=${START_SCRIPT}"
echo "EPAPER_BASE_DIR=${EPAPER_BASE_DIR}"
echo "============================================================"

# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

if [ ! -d "${PROJECT_DIR}" ]; then
  echo "[ERROR] PROJECT_DIR not found: ${PROJECT_DIR}"
  exit 1
fi

if [ ! -d "${API_DIR}" ]; then
  echo "[ERROR] API_DIR not found: ${API_DIR}"
  exit 1
fi

if [ ! -f "${PY_SCRIPT}" ]; then
  echo "[ERROR] Python script not found: ${PY_SCRIPT}"
  exit 1
fi

if [ ! -x "${VENV_PY}" ]; then
  echo "[ERROR] venv python not found or not executable: ${VENV_PY}"
  echo "Please create venv or update VENV_PY in this setup script."
  exit 1
fi

if [ ! -d "${EPAPER_BASE_DIR}" ]; then
  echo "[ERROR] EPAPER_BASE_DIR not found: ${EPAPER_BASE_DIR}"
  echo "Please confirm Waveshare 3in7_e-Paper_G files exist."
  echo "Hint:"
  echo "  find ${PROJECT_DIR} -iname epd3in7g.py"
  exit 1
fi

if [ ! -f "${EPAPER_BASE_DIR}/lib/waveshare_epd/epd3in7g.py" ]; then
  echo "[ERROR] epd3in7g.py not found under EPAPER_BASE_DIR:"
  echo "  ${EPAPER_BASE_DIR}/lib/waveshare_epd/epd3in7g.py"
  exit 1
fi

mkdir -p "${LOG_DIR}"

# ------------------------------------------------------------
# Create start script
# ------------------------------------------------------------

cat > "${START_SCRIPT}" <<EOF
#!/usr/bin/env bash

# ============================================================
# Auto start script for qr_tx_display3in7g.py
# Generated by setup_cron_qr_tx_display3in7g.sh
# ============================================================

sleep 60

PROJECT_DIR="${PROJECT_DIR}"
API_DIR="\${PROJECT_DIR}/api"
VENV_PY="\${PROJECT_DIR}/venv/bin/python3"
SCRIPT="\${API_DIR}/qr_tx_display3in7g.py"
LOG_DIR="\${PROJECT_DIR}/logs"
LOG_FILE="\${LOG_DIR}/qr_tx_display3in7g_startup.log"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export GPIOZERO_PIN_FACTORY="lgpio"
export EPAPER_BASE_DIR="${EPAPER_BASE_DIR}"
export NODE_BIN="/usr/bin/node"
export NODE_ID="node-s-3in7g"
export CSV_FILENAME="qr_tx_log_yamalog_epaper_3in7g.csv"
export DISPLAY_HOLD_SEC="180"
export N_TRIALS="0"
export SEND_JS="send_set_value.js"

mkdir -p "\${LOG_DIR}"

{
  echo "=================================================="
  echo "[START] \$(date '+%Y-%m-%d %H:%M:%S')"
  echo "USER=\$(whoami)"
  echo "PROJECT_DIR=\${PROJECT_DIR}"
  echo "API_DIR=\${API_DIR}"
  echo "SCRIPT=\${SCRIPT}"
  echo "PYTHON=\${VENV_PY}"
  echo "NODE_BIN=\${NODE_BIN}"
  echo "EPAPER_BASE_DIR=\${EPAPER_BASE_DIR}"
  echo "PATH=\${PATH}"
  echo "spidev:"
  ls -l /dev/spidev* 2>&1 || true
  echo "gpiochip:"
  ls -l /dev/gpiochip* 2>&1 || true
} >> "\${LOG_FILE}" 2>&1

cd "\${API_DIR}" || {
  echo "[ERROR] cd failed: \${API_DIR}" >> "\${LOG_FILE}" 2>&1
  exit 1
}

exec "\${VENV_PY}" "\${SCRIPT}" >> "\${LOG_FILE}" 2>&1
EOF

chmod +x "${START_SCRIPT}"

echo "[OK] Created start script:"
echo "  ${START_SCRIPT}"

# ------------------------------------------------------------
# Register cron
# ------------------------------------------------------------

TMP_CRON="$(mktemp)"

crontab -l 2>/dev/null | grep -v "start_qr_tx_display3in7g.sh" > "${TMP_CRON}" || true
echo "${CRON_LINE}" >> "${TMP_CRON}"

crontab "${TMP_CRON}"
rm -f "${TMP_CRON}"

echo "[OK] Registered cron @reboot:"
echo "  ${CRON_LINE}"

# ------------------------------------------------------------
# Show current cron
# ------------------------------------------------------------

echo "============================================================"
echo "Current crontab:"
crontab -l
echo "============================================================"

echo "[DONE]"
echo ""
echo "Manual test:"
echo "  ${START_SCRIPT}"
echo ""
echo "Log check:"
echo "  tail -f ${STARTUP_LOG}"
echo ""
echo "After reboot:"
echo "  sudo reboot"
echo "  tail -n 150 ${STARTUP_LOG}"
